/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGateRouteRouteImport } from './routes/admin/_gate/route'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as PackagesIdRouteImport } from './routes/packages_/$id'
import { Route as AdminGateCustomRequestsRouteImport } from './routes/admin/_gate/custom-requests'
import { Route as AdminGateDashboardRouteImport } from './routes/admin/_gate/dashboard'
import { Route as AdminGateHotelsRouteImport } from './routes/admin/_gate/hotels'
import { Route as AdminGateInquiriesRouteImport } from './routes/admin/_gate/inquiries'
import { Route as AdminGateMediaRouteImport } from './routes/admin/_gate/media'
import { Route as AdminGateServicesRouteImport } from './routes/admin/_gate/services'
import { Route as AdminGateWebsiteContentRouteImport } from './routes/admin/_gate/website-content'
import { Route as AdminGatePackagesIndexRouteImport } from './routes/admin/_gate/packages.index'
import { Route as AdminGatePackagesIdRouteImport } from './routes/admin/_gate/packages.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRouteRoute = AdminGateRouteRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages_/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateCustomRequestsRoute = AdminGateCustomRequestsRouteImport.update({
  id: '/custom-requests',
  path: '/custom-requests',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateDashboardRoute = AdminGateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateHotelsRoute = AdminGateHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateInquiriesRoute = AdminGateInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateMediaRoute = AdminGateMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateServicesRoute = AdminGateServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateWebsiteContentRoute = AdminGateWebsiteContentRouteImport.update({
  id: '/website-content',
  path: '/website-content',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGatePackagesIndexRoute = AdminGatePackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGatePackagesIdRoute = AdminGatePackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => AdminGateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminGateRouteRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/packages/$id': typeof PackagesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/custom-requests': typeof AdminGateCustomRequestsRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/hotels': typeof AdminGateHotelsRoute
  '/admin/inquiries': typeof AdminGateInquiriesRoute
  '/admin/media': typeof AdminGateMediaRoute
  '/admin/services': typeof AdminGateServicesRoute
  '/admin/website-content': typeof AdminGateWebsiteContentRoute
  '/admin/packages/$id': typeof AdminGatePackagesIdRoute
  '/admin/packages/': typeof AdminGatePackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/packages/$id': typeof PackagesIdRoute
  '/admin/custom-requests': typeof AdminGateCustomRequestsRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/hotels': typeof AdminGateHotelsRoute
  '/admin/inquiries': typeof AdminGateInquiriesRoute
  '/admin/media': typeof AdminGateMediaRoute
  '/admin/services': typeof AdminGateServicesRoute
  '/admin/website-content': typeof AdminGateWebsiteContentRoute
  '/admin/packages/$id': typeof AdminGatePackagesIdRoute
  '/admin/packages': typeof AdminGatePackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_gate': typeof AdminGateRouteRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/packages_/$id': typeof PackagesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_gate/custom-requests': typeof AdminGateCustomRequestsRoute
  '/admin/_gate/dashboard': typeof AdminGateDashboardRoute
  '/admin/_gate/hotels': typeof AdminGateHotelsRoute
  '/admin/_gate/inquiries': typeof AdminGateInquiriesRoute
  '/admin/_gate/media': typeof AdminGateMediaRoute
  '/admin/_gate/services': typeof AdminGateServicesRoute
  '/admin/_gate/website-content': typeof AdminGateWebsiteContentRoute
  '/admin/_gate/packages/$id': typeof AdminGatePackagesIdRoute
  '/admin/_gate/packages/': typeof AdminGatePackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/packages/$id'
    | '/admin/'
    | '/admin/custom-requests'
    | '/admin/dashboard'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/services'
    | '/admin/website-content'
    | '/admin/packages/$id'
    | '/admin/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/packages/$id'
    | '/admin/custom-requests'
    | '/admin/dashboard'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/services'
    | '/admin/website-content'
    | '/admin/packages/$id'
    | '/admin/packages'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/admin/_gate'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/packages_/$id'
    | '/admin/'
    | '/admin/_gate/custom-requests'
    | '/admin/_gate/dashboard'
    | '/admin/_gate/hotels'
    | '/admin/_gate/inquiries'
    | '/admin/_gate/media'
    | '/admin/_gate/services'
    | '/admin/_gate/website-content'
    | '/admin/_gate/packages/$id'
    | '/admin/_gate/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminGateRouteRoute: typeof AdminGateRouteRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  PackagesIdRoute: typeof PackagesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages_/$id': {
      id: '/packages_/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate/custom-requests': {
      id: '/admin/_gate/custom-requests'
      path: '/custom-requests'
      fullPath: '/admin/custom-requests'
      preLoaderRoute: typeof AdminGateCustomRequestsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/dashboard': {
      id: '/admin/_gate/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGateDashboardRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/hotels': {
      id: '/admin/_gate/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminGateHotelsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/inquiries': {
      id: '/admin/_gate/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminGateInquiriesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/media': {
      id: '/admin/_gate/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminGateMediaRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/services': {
      id: '/admin/_gate/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminGateServicesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/website-content': {
      id: '/admin/_gate/website-content'
      path: '/website-content'
      fullPath: '/admin/website-content'
      preLoaderRoute: typeof AdminGateWebsiteContentRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/packages/': {
      id: '/admin/_gate/packages/'
      path: '/packages'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AdminGatePackagesIndexRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/packages/$id': {
      id: '/admin/_gate/packages/$id'
      path: '/packages/$id'
      fullPath: '/admin/packages/$id'
      preLoaderRoute: typeof AdminGatePackagesIdRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
  }
}

interface AdminGateRouteRouteChildren {
  AdminGateCustomRequestsRoute: typeof AdminGateCustomRequestsRoute
  AdminGateDashboardRoute: typeof AdminGateDashboardRoute
  AdminGateHotelsRoute: typeof AdminGateHotelsRoute
  AdminGateInquiriesRoute: typeof AdminGateInquiriesRoute
  AdminGateMediaRoute: typeof AdminGateMediaRoute
  AdminGateServicesRoute: typeof AdminGateServicesRoute
  AdminGateWebsiteContentRoute: typeof AdminGateWebsiteContentRoute
  AdminGatePackagesIdRoute: typeof AdminGatePackagesIdRoute
  AdminGatePackagesIndexRoute: typeof AdminGatePackagesIndexRoute
}

const AdminGateRouteRouteChildren: AdminGateRouteRouteChildren = {
  AdminGateCustomRequestsRoute: AdminGateCustomRequestsRoute,
  AdminGateDashboardRoute: AdminGateDashboardRoute,
  AdminGateHotelsRoute: AdminGateHotelsRoute,
  AdminGateInquiriesRoute: AdminGateInquiriesRoute,
  AdminGateMediaRoute: AdminGateMediaRoute,
  AdminGateServicesRoute: AdminGateServicesRoute,
  AdminGateWebsiteContentRoute: AdminGateWebsiteContentRoute,
  AdminGatePackagesIdRoute: AdminGatePackagesIdRoute,
  AdminGatePackagesIndexRoute: AdminGatePackagesIndexRoute,
}

const AdminGateRouteRouteWithChildren = AdminGateRouteRoute._addFileChildren(
  AdminGateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminGateRouteRoute: AdminGateRouteRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  PackagesIdRoute: PackagesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
